title: Digital tools for workflow and project management
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/workflow-tools/\">View in GitHub</a>"
